# Generated by Django 5.1.2 on 2024-10-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoey', '0002_zproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='zproduct',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
