# Generated by Django 5.1.3 on 2025-09-08 18:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InboundFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("filename", models.CharField(max_length=255)),
                ("checksum", models.CharField(max_length=64)),
                ("adapter_key_used", models.CharField(max_length=255)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("manifest", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(default="pending", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("external_id", models.CharField(max_length=64)),
                ("name", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "unique_together": {("provider", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="InboundEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adapter_key", models.CharField(max_length=255)),
                ("transport", models.CharField(max_length=32)),
                ("trigger_mode", models.CharField(max_length=32)),
                ("cursor", models.JSONField(blank=True, null=True)),
                ("flags", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField()),
                ("status", models.CharField(default="pending", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["adapter_key", "status"],
                        name="ingest_inbo_adapter_3bfd25_idx",
                    ),
                    models.Index(
                        fields=["transport", "trigger_mode"],
                        name="ingest_inbo_transpo_da006f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=64)),
                ("source_order_id", models.CharField(max_length=64)),
                ("currency", models.CharField(max_length=8)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("raw", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ingest.customer",
                    ),
                ),
            ],
            options={
                "unique_together": {("provider", "source_order_id")},
            },
        ),
        migrations.CreateModel(
            name="OrderLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(max_length=64)),
                ("quantity", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="ingest.order",
                    ),
                ),
            ],
        ),
    ]
